Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2022-10, with the labels that each got.

#1655 refactor: count Carpentry skill towards Skill Average
  src/constants/skills.js
  src/lib.js
  views/stats.ejs
Labels: waiting

#1661 refactor: update minions
  views/stats.ejs
Labels: needs testing

#1693 fix enrichments v2
  src/lib.js
  views/stats.ejs
Labels: ready to merge

#1648 feat: Add equipment
  public/resources/ts/calculate-player-stats.ts
  public/resources/ts/stats-defer.ts
  src/lib.js
  views/stats.ejs
Labels: ready to merge

#1651 feat: add bestiary
  src/constants.js
  src/constants/bestiary.js
  src/lib.js
  views/stats.ejs
Labels: ready to merge

#1695 convert coment into jsDoc
  common/constants/stats.js
Labels: ready to merge

#1680 [0.12.3] M7 Update: Catacombs level above 50
  public/resources/ts/calculate-player-stats.ts
  src/lib.js
  src/weight/senither-weight.js
Labels: ready to merge

#1659 feat: add Crimson Isle Stats
  src/constants/misc.js
  src/lib.js
  views/stats.ejs
Labels: ready to merge

#1650 feat: proper recomb accessory count
  src/constants/accessories.js
  views/stats.ejs
Labels: ready to merge

#1738 fix: bestiary level and dojo points
  src/constants/bestiary.js
  views/stats.ejs
Labels: bug, ready to merge

#1718 Switch to PNPM
  .github/dependabot.yml
  .github/workflows/ci-cd.yml
  .gitignore
  .prettierignore
  CONTRIBUTING.md
  Dockerfile
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
  rollup.config.js
Labels: dont merge yet

#1740 Minor UX tweaks
  public/resources/scss/stats.scss
Labels: enhancement
