Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-02, with the labels that each got.

#1829 build(deps): update skyhelper-networth to 1.11.0
  package.json
  pnpm-lock.yaml
Labels: ready to merge

#1840 fix: error if player doesn't have selected profile
  src/lib.js
Labels: ready to merge

#1864 fix: some plugins don't like rollup 3
  package.json
  pnpm-lock.yaml
  rollup.config.js
Labels: size/M

#1836 refactor: missing accessories system
  src/constants/accessories.js
  src/helper.js
  src/lib.js
  src/scripts/update-bazaar.js
  views/stats.ejs
Labels: size/XXL

#1857 feat: add supprot for class level above 50
  src/lib.js
  views/stats.ejs
Labels: size/M

#1873 fix: area names
  src/constants/misc.js
Labels: size/XS

#1874 feat: add new enchantments
  common/constants/enchantments.js
Labels: size/XS

#1875 fix: fairy souls count
  src/constants/misc.js
Labels: size/XS

#1879 fix: dungeon journals being outdated
  src/constants/dungeons.js
  src/lib.js
  views/stats.ejs
Labels: size/M

#1876 ci: Update Github Actions
  .github/workflows/ci-cd.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/greetings.yml
  .github/workflows/stale.yml
Labels: size/L

#1858 feat: add new firesale skins
  src/constants/skins-animations.js
Labels: size/S

#1882 fix: some items missing rarity
  src/scripts/update-items.js
Labels: size/XS

#1870 fix: SkyBlock Level bar width
  public/resources/scss/stats.scss
Labels: size/XS

#1886 fix: accessory rarity being undefined
  src/lib.js
Labels: size/XS

#1884 refactor: add `LandonHP` to blocked players
  src/constants/misc.js
Labels: size/XS
