Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-03, with the labels that each got.

#1890 fix: Magical Power being 2x
  src/lib.js
Labels: size/XS

#1888 fix: dungeon journals being undefined sometimes
  src/lib.js
Labels: size/XS

#1891 fix: text not being gold at unique medal
  views/stats.ejs
Labels: size/XS

#1892 refactor: update description content
  views/stats.ejs
Labels: size/M

#1885 fix: axes missing in farming tools
  src/constants/items.js
  src/helper.js
  src/lib.js
Labels: size/M

#1897 fix: highest critical damage format
  views/stats.ejs
Labels: size/XS

#1893 fix: integer limit breaking cultivating
  src/lib.js
  views/stats.ejs
Labels: size/XS

#1899 refactor: `Price Paid at Dark Auction:` color
  src/lib.js
Labels: size/XS

#1901 feat: add `Crystal Hollows` to Area Names
  src/constants/misc.js
Labels: size/XS

#1855 feat: add `Item Value:` to pets
  package.json
  pnpm-lock.yaml
  src/lib.js
Labels: size/S

#1860 feat: remade pack selection menu
  .prettierignore
  includes/header.ejs
  misc/benchmarks/get-texture.js
  package.json
  pnpm-lock.yaml
  public/resourcepacks/SkyBlock Stats/pack.mcmeta
  public/resourcepacks/Vanilla/assets/minecraft/mcpatcher/cit/.gitkeep
  public/resourcepacks/Vanilla/config.json
  public/resourcepacks/Vanilla/pack.mcmeta
  public/resourcepacks/Vanilla/pack.png
  public/resources/scss/shared.scss
  public/resources/ts/common-defer.ts
  public/resources/ts/elements/pack-list.ts
  public/resources/ts/globals.d.ts
  public/resources/ts/stats-defer.ts
  rollup.config.js
  src/app.js
  src/custom-resources.js
  src/helper.js
  src/helper/cache.js
  src/helper/item.js
  src/lib.js
  src/renderer.js
  src/routes/cape.js
  src/routes/head.js
  src/routes/item.js
  src/routes/leather.js
  src/routes/potion.js
  src/routes/texture.js
  src/scripts/prepare-cache.js
Labels: size/XXL

#1903 fix: `renderLore()` not clearing format
  common/formatting.js
Labels: size/XS

#1909 feat: add Nutcracker to sea creautres
  public/resources/img/sea_creatures/nutcracker.png
  public/resources/img/sea_creatures/nutcracker.webp
  views/stats.ejs
Labels: size/XS

#1908 fix: Taurus Sea Creature having wrong ID
  public/resources/img/sea_creatures/pig_rider.png
  public/resources/img/sea_creatures/pig_rider.webp
  src/constants/misc.js
  views/stats.ejs
Labels: size/XS

#1902 fix: incorrect pet lores
  src/constants/pet-stats.js
  src/constants/pets.js
  src/lib.js
Labels: size/L

#1910 fix: Golden Dragon Pet Stats being NaN
  src/constants/pet-stats.js
Labels: size/XS

#1911 feat: add new enchantments added in Garden v2
  common/constants/enchantments.js
  src/constants/items.js
Labels: size/XS

#1912 feat: new Garden Accessories
  src/constants/accessories.js
Labels: size/XS

#1907 fix: `renderLore()` breaking with `§L`
  common/formatting.js
Labels: size/XS
