Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-10, with the labels that each got.

#2039 [URGENT] fix: API throwing an error because of bingo Profile
  src/custom-resources.js
  src/lib.js
  src/routes/api/collections.js
  src/routes/api/skills.js
  src/routes/apiv2/coins.js
  src/routes/apiv2/profile.js
  src/routes/apiv2/slayers.js
Labels: size/M

#2040 feat: new pet Skins
  src/constants/skins-animations.js
Labels: size/S

#2004 Add skycrypt main to docker container
  docker-compose.yml
Labels: size/XS

#2047 fix: Hypixel Throwing an error when no Bingo Profile
  src/lib.js
Labels: size/XS

#2048 fix: resource packs being unselectable
  src/custom-resources.js
Labels: size/XS

#2021 feat: add S/R and Blood Mob Kills
  src/lib.js
  views/stats.ejs
Labels: size/S

#1941 refactor: full-install of docker compose environment
  docker-compose.yml
  nginx.conf
  src/credentials.js
Labels: size/M

#1900 refactor: hide locked / empty information
  src/lib.js
  views/stats.ejs
Labels: size/S

#2041 feat: add `kuudra` to `AREA_NAMES`
  src/constants/misc.js
Labels: size/XS

#2042 fix: no GM existing throwing an error
  src/helper.js
Labels: size/XS

#2043 feat: add new Halloween pet skin
  src/constants/skins-animations.js
Labels: size/XS

#2044 fix: Wisp Pet Lore
  src/constants/pet-stats.js
Labels: size/S

#2046 fix: baby dragon pet skin
  src/constants/skins-animations.js
Labels: size/XS

#2052 Add DuckySoLucky and WarpWing
  src/scripts/update-featured-profiles.js
Labels: size/S

#2059 [VERY URGENT] fix: error with pets, add new Eerie pet
  src/constants/pet-stats.js
  src/constants/pets.js
  src/lib.js
Labels: size/M

#2060 feat: add `INTIMIDATION_RELIC` to upgrades
  src/constants/accessories.js
Labels: size/XS

#2049 fix: max SkyBlock Level
  src/constants/leveling.js
  src/helper/leaderboards.js
  src/lib.js
Labels: size/M

#2061 fix: HOTM tree descriptions
  src/constants/hotm.js
Labels: size/S

#2062 feat: add `Kazius1` to blacklist
  src/constants/misc.js
Labels: size/XS

#2057 Fix: mooshroom cow farming fortune formula
  src/constants/pet-stats.js
Labels: size/XS

#2065 fix: add new Diamond Goblin
  src/constants/bestiary.js
Labels: size/XS

#2068 refactor: remove `Math.max()` for skyblockLevelCap
  src/constants/leveling.js
Labels: size/XS

#2063 fix endermite skin
  src/constants/skins-animations.js
Labels: size/XS

#2067 feat: new August Pet skins
  src/constants/skins-animations.js
Labels: size/S

#2066 fix: catacombs skill experience calculation
  src/lib.js
Labels: size/XS
