Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-11, with the labels that each got.

#1987 fix: rewrite missing accessories system
  src/app.js
  src/constants/accessories.js
  src/helper.js
  src/lib.js
  views/stats.ejs
Labels: size/L

#2069 Fix mythic black cat and eerie pet
  src/constants/pet-stats.js
  src/constants/pets.js
Labels: size/S

#2070 fix: skyblock level lb position
  src/lib.js
Labels: size/XS

#2071 feat: uncommon party hat Pet Item
  src/constants/pets.js
Labels: size/XS

#2073 fix: Total Crop Weight
  views/stats.ejs
Labels: size/XS

#2074 fix: Glacial Wisp Pet Perk
  src/constants/pet-stats.js
Labels: size/XS

#2076 fix: renovate not updating skyhelper-networth package
  renovate.json
Labels: size/XS

#2077 feat: add primalFear kills to Eerie pet
  src/constants/pet-stats.js
Labels: size/XS

#2078 fix: candy bag not being viewable
  public/resources/ts/stats-defer.ts
  src/lib.js
Labels: size/XS

#2075 fix: skyblock level gold bar maxed at lvl instead of xp
  public/resources/ts/elements/skill-component.ts
  public/resources/ts/globals.d.ts
  src/constants/leveling.js
  src/lib.js
Labels: size/M

#2081 fix: renovate.json
  renovate.json
Labels: size/XS

#2088 fix: few fixes and refactor
  public/resources/ts/globals.d.ts
  public/resources/ts/stats-defer.ts
  src/app.js
  src/custom-resources.js
  src/stats/enchanting.js
  src/stats/items.js
  src/stats/minions.js
  views/sections/stats/basic_stats.ejs
  views/sections/stats/collections.ejs
  views/sections/stats/items/wardrobe.ejs
  views/sections/stats/minions.ejs
Labels: size/L

#2096 fix & refactor: fixes and refactors
  src/app.js
  src/helper.js
  src/lib.js
  src/stats/collections.js
  src/stats/misc.js
  src/stats/rift.js
  views/sections/stats/misc/mythological_event.ejs
Labels: size/M
