Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-12, with the labels that each got.

#2105 fix: effects erroring
  src/stats/misc.js
Labels: size/XS

#2099 fix: white flash bang screen
  src/app.js
Labels: size/S

#2100 fix: TimeDeo Guild GM beign null
  views/stats.ejs
Labels: size/XS

#2101 fix: boss collections being incorrect and missing info
  src/constants/collections.js
  src/stats/collections.js
  views/sections/stats/collections.ejs
Labels: size/M

#2095 feat: add new Novemember 2023 Pet Skins
  src/constants/skins-animations.js
Labels: size/S

#2104 fix: dungeons data not being hidden when emtpy
  src/stats/collections.js
  src/stats/dungeons.js
  views/sections/stats/slayer.ejs
Labels: size/S

#2106 fix: timecharm order not being correct if player doesn't collect them…
  src/constants/rift.js
  src/stats/rift.js
Labels: size/S

#2111 fix: deaths beign undefined
  src/stats/misc.js
Labels: size/XS

#2113 fix: pet milestone percentage being NaN
  src/stats/misc.js
Labels: size/XS

#2117 [SEMI URGENT] feat: add back leaderboards
  src/app.js
  src/lib.js
  src/stats.js
  src/stats/dungeons.js
  src/stats/items.js
  src/stats/leaderboards.js
  src/stats/missing.js
  src/stats/pets.js
Labels: size/L

#2122 [URGENT] perf & refactor: don't fetch guild on profile load
  public/resources/ts/elements/guild-button.ts
  public/resources/ts/globals.d.ts
  public/resources/ts/stats-defer.ts
  src/helper.js
  src/lib.js
  src/routes/apiv2.js
  src/routes/apiv2/guild.js
  src/scripts/init-collections.js
  views/stats.ejs
Labels: size/L

#2125 [URGENT] fix: museum lore causing memory leaks
  src/stats/items/museum.js
Labels: size/XS

#2131 [HIGH PRIORITY] feat: add proper error handling
  public/resources/ts/calculate-player-stats.ts
  src/app.js
  src/helper.js
  src/lib.js
  src/stats/collections.js
  views/stats.ejs
Labels: size/L

#2118 fix: profile gamemode beign undefined
  views/stats.ejs
Labels: size/XS

#2137 fix: LB error
  src/stats/leaderboards.js
Labels: size/XS

#2107 feat: add new Dec 2023 Pet Skins
  src/constants/skins-animations.js
Labels: size/M

#2108 feat: add new ice essence sohp perk
  src/constants/misc.js
Labels: size/XS

#2109 feat: add Mythic Snowman Pet
  src/constants/pet-stats.js
  src/constants/pets.js
  src/stats/pets.js
Labels: size/S

#2110 fix: dwarven mines data being hidden if player hasn't entered c hollows
  views/sections/stats/skills/mining.ejs
Labels: size/XS

#2112 fix: bingo card progress bar
  src/stats/bingo.js
Labels: size/XS

#2120 fix: embed format
  views/stats.ejs
Labels: size/XS

#2126 fix: add long sword to swords cateogry
  src/constants/items.js
Labels: size/XS

#2128 feat: add Hypixel Plus to credits
  includes/header.ejs
Labels: size/XS

#2129 fix: bestiary constants
  src/constants/bestiary.js
Labels: size/M

#2121 fix: show timecharms and pohrtals only if unlocked
  views/sections/stats/rift.ejs
Labels: size/M

#2127 feat: add owl pet
  common/constants/stats.js
  src/constants/pet-stats.js
  src/constants/pets.js
  src/stats/pets.js
Labels: size/M

#2130 fix: rarity order in auctions
  src/stats/misc.js
  views/sections/stats/misc/auctions.ejs
Labels: size/S

#2132 feat: add new December 2023 pet skins
  src/constants/skins-animations.js
Labels: size/M

#2134 fix: hide Uncategorized values if they're 0
  views/sections/stats/misc/uncategorized.ejs
Labels: size/XS

#2135 refactor: update README.md image
  public/resources/img/screenshots/windows-0.jpg
Labels: size/XS

#2136 feat: implement museum into NW calculation
  package.json
  pnpm-lock.yaml
  src/lib.js
  views/sections/stats/basic_stats.ejs
Labels: size/M

#2138 fix some small grammar issues
  views/sections/stats/dungeons.ejs
  views/sections/stats/skills/mining.ejs
  views/sections/stats/slayer.ejs
Labels: size/XS

#2139 fix: error caused my museum items
  src/lib.js
  src/stats/misc.js
Labels: size/S
