Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-07, with the labels that each got.

#1982 Feat rift
  src/constants.js
  src/constants/rift.js
  src/lib.js
  views/stats.ejs
Labels: size/L

#1961 rift
  src/constants.js
  src/constants/rift.js
  src/lib.js
  views/stats.ejs
Labels: size/L

#1977 feat: add `agarimoo` to sea creature list
  public/resources/img/sea_creatures/agarimoo.png
  public/resources/img/sea_creatures/agarimoo.webp
  views/stats.ejs
Labels: size/XS

#1975 fix: fairy souls 140 -> 142
  src/constants/misc.js
Labels: size/XS

#1898 fix: lower rarity accessories having higher priority, same accessory duplicates and `Unique Accessories:` incorrect value
  pnpm-lock.yaml
  src/lib.js
Labels: size/L

#1942 feat: credits & change format
  includes/header.ejs
  views/stats.ejs
Labels: size/M

#1895 Farming weight
  includes/header.ejs
  src/lib.js
  src/scripts/update-featured-profiles.js
  src/weight/farming-weight.js
  views/stats.ejs
Labels: size/L

#1973 Updating explanations on how to correctly obtain API keys
  CONTRIBUTING.md
  README.md
  src/app.js
Labels: size/XS
