Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-06, with the labels that each got.

#1921 build(deps): bump skyhelper-networth to 1.12.10
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#1945 Add Hypixel+ to the Custom Textures Credits
  README.md
Labels: size/XS

#1946 fix: MP from Hegemony Artifact
  src/helper.js
  src/lib.js
Labels: size/M

#1947 fix: Catacombs skills being maxed all time
  src/lib.js
Labels: size/S

#1937 feat: Personal Compactor/Deletor item preview
  src/helper.js
  src/lib.js
Labels: size/M

#1853 Account For Finnegan Perk and Correct Medal Brackets
  src/lib.js
Labels: size/M

#1883 fix: `formatNumber()` rounding issue
  common/formatting.js
  src/lib.js
Labels: size/M

#1957 Feat vampire slayer
  src/constants/leveling.js
  src/lib.js
  src/weight/senither-weight.js
  views/stats.ejs
Labels: size/M

#1958 feat: add new Rift accessories
  src/constants/accessories.js
Labels: size/XS

#1953 feat: add new 4th Anniversary accessories
  src/constants/accessories.js
Labels: size/XS

#1952 fix: `/item` Endpoint not being able to return vanilla items
  src/helper/item.js
  src/renderer.js
  src/routes/item.js
Labels: size/S

#1665 feat: add trophyFish
  public/resources/scss/stats.scss
  src/constants.js
  src/constants/trophy-fish.js
  src/lib.js
  views/stats.ejs
Labels: size/L

#1954 fix: `hypixelItem` being null
  src/lib.js
Labels: size/S

#1965 fix: div tag missing `<`
  views/stats.ejs
Labels: size/XS

#1964 feat: add Rift to `AREA_NAMES`
  src/constants/misc.js
Labels: size/XS

#1967 fix: slayer order
  views/stats.ejs
Labels: size/XS

#1956 feat: add new pet skins released in June
  src/constants/skins-animations.js
Labels: size/S

#1960 Refactor: Zombie Pet Lore
  common/constants/stats.js
  src/constants/pet-stats.js
Labels: size/S

#1963 feat: add new Rift Enchantments
  common/constants/enchantments.js
Labels: size/XS

#1968 refactor: ignore untransferable rift accessories
  src/constants/accessories.js
Labels: size/S

#1962 feat: rift pet changes
  common/constants/stats.js
  package.json
  pnpm-lock.yaml
  src/constants/pet-stats.js
  src/constants/pets.js
  src/lib.js
Labels: size/L

#1971 Refactor: MaxLevel
  src/lib.js
Labels: size/XS
