Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2023-08, with the labels that each got.

#1992 fix: POTM texture
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/perks/peak/potm_vi.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/perks/peak/potm_vi.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/perks/peak/potm_vii.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/perks/peak/potm_vii.properties
Labels: size/S

#1991 fix: spider slayer 7 reward
  common/constants/bonuses.js
Labels: size/XS

#1976 fix: trophy fish descriptions
  src/constants/trophy-fish.js
Labels: size/XS

#1974 Adding Vampire Minion and Rift collections
  src/constants/minions.js
  views/stats.ejs
Labels: size/XS

#1994 feat: add `McGrubber's Burger` to rift section
  src/constants/rift.js
  src/lib.js
  views/stats.ejs
Labels: size/XS

#1990 feat: add new Bingo Pet Item
  src/constants/pets.js
Labels: size/XS

#1980 fix: Montezuma pet being inactive
  src/constants/pet-stats.js
  src/constants/pets.js
  src/lib.js
Labels: size/S

#1985 fix: hide kicked coop members
  src/lib.js
Labels: size/XS

#1995 fix: skill average being incorrect
  src/lib.js
Labels: size/XS

#1993 feat: new Pet skins
  src/constants/skins-animations.js
Labels: size/S

#1998 fix: incorrect pet description stats
  src/constants/pet-stats.js
Labels: size/XS

#2002 fix: Default Leather Armor throwing an error
  src/lib.js
Labels: size/XS

#2003 fix: members being null
  src/lib.js
Labels: size/XS

#1877 fix: error thrown if guild isn't in ur db (first search only)
  src/helper.js
  views/stats.ejs
Labels: size/L

#1996 fix: bestiary
  public/resources/scss/stats.scss
  src/app.js
  src/constants/bestiary.js
  src/lib.js
  src/stats.js
  src/stats/bestiary.js
  views/sections/stats/bestiary.ejs
  views/stats.ejs
Labels: size/XXL

#2012 fix: GreatExplorer HOTM perk
  src/constants/hotm.js
Labels: size/XS

#2013 fix: profile switching not working because new profile_id length
  src/lib.js
Labels: size/XS

#2014 refactor: `Porhtals` -> `Eyes` Unlocked
  views/stats.ejs
Labels: size/XS

#2015 refactor: strike through members instead of hiding
  public/resources/scss/stats.scss
  src/lib.js
  views/stats.ejs
Labels: size/S

#2011 fix: pet descriptions, stats, new rewards
  common/constants/rewards.js
  src/constants/pet-stats.js
  src/constants/pets.js
  src/lib.js
  views/stats.ejs
Labels: size/M

#1872 feat: add leaderboard positions
  src/helper/leaderboards.js
  src/lib.js
  src/routes/apiv2/dungeons.js
Labels: size/M
