Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-10, with the labels that each got.

#2283 fix(helper): add 'CHISEL' gemstone type
  src/helper.js
Labels: size/XS

#2284 build(deps): bump sh-nw package
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#2285 merge development into production
  package.json
  pnpm-lock.yaml
  src/constants/weight/farming-weight.js
  src/helper.js
  src/lib.js
  src/stats/farming.js
  src/stats/items.js
  views/sections/stats/basic_stats.ejs
  views/sections/stats/bestiary.ejs
  views/sections/stats/bingo.ejs
  views/sections/stats/collections.ejs
  views/sections/stats/crimson_isle.ejs
  views/sections/stats/items/accessories.ejs
  views/sections/stats/items/inventory.ejs
  views/sections/stats/minions.ejs
  views/sections/stats/misc.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/pets.ejs
  views/sections/stats/rift.ejs
  views/sections/stats/skills.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/sections/stats/slayer.ejs
  views/stats.ejs
Labels: size/XXL

#2286 fix: attempted fix before resorting to revert
  pnpm-lock.yaml
Labels: size/S

#2287 fix: hotm
  common/constants/stats.js
  src/constants/hotm.js
Labels: size/XXL

#2301 fix: farming weight when pests missing
  src/constants/weight/farming-weight.js
Labels: size/XS

#2302 merge development into production
  includes/header.ejs
  package.json
  pnpm-lock.yaml
  public/resources/ts/globals.d.ts
  src/constants/hotm.js
  src/constants/weight/farming-weight.js
  src/constants/weight/lily-weight.js
  src/constants/weight/senither-weight.js
  src/stats/weight.js
  views/sections/stats/basic_stats.ejs
Labels: size/L

#2303 fix: skeleton key forge time
  src/constants/forge.js
Labels: size/L

#2300 Change Frozen Skin Description
  src/constants/misc.js
Labels: size/XS

#2304 feat: update essence shop
  src/constants/misc.js
Labels: size/M

#2305 merge development into production
  src/constants/forge.js
  src/constants/misc.js
Labels: size/L
