Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-12, with the labels that each got.

#2313 fix: Gdrag's MF and Strength being NaN when player have collection api off
  src/constants/pet-stats.js
Labels: size/XS

#2315 fix: theme replacing `r` and `l` with `w` in color codes
  src/constants/themes/april-fools-2024/formatting.js
Labels: size/XS

#2319 fix: Mole using `this.level` for calculations instead of `level`, "Blockhead" misstyped as "Block Head"
  src/constants/hotm.js
Labels: size/S

#2316 Updated Museum items
  src/constants/museum.js
Labels: size/XXL

#2314 Fix: new forgeable pets able to display forge timing
  src/constants/forge.js
  src/constants/pet-stats.js
  src/stats/mining.js
Labels: size/M
