Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-02, with the labels that each got.

#2177 fix: Update dependency, fix skin rendering, fix redis connection,
  misc/benchmarks/get-texture.js
  package.json
  pnpm-lock.yaml
  public/resources/html/offline.html
  public/resources/scss/_fonts.scss
  public/resources/scss/index.scss
  public/resources/scss/shared.scss
  public/resources/scss/stats.scss
  public/resources/ts/calculate-player-stats.ts
  public/resources/ts/common-defer.ts
  public/resources/ts/development-defer.ts
  public/resources/ts/elements/bonus-stats.ts
  public/resources/ts/elements/guild-button.ts
  public/resources/ts/elements/inventory-view.ts
  public/resources/ts/elements/pack-list.ts
  public/resources/ts/elements/player-stat.ts
  public/resources/ts/elements/rich-item.ts
  public/resources/ts/elements/skill-component.ts
  public/resources/ts/elements/theme-list.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  public/resources/ts/tsconfig.json
  public/sw.js
  src/app.js
  src/constants/accessories.js
  src/constants/hotm.js
  src/constants/leveling.js
  src/constants/pet-stats.js
  src/constants/weight/lily-weight.js
  src/credentials.js
  src/custom-resources.js
  src/hashes.js
  src/helper.js
  src/lib.js
  src/main.js
  src/redis.js
  src/renderer.js
  src/routes/api/collections.js
  src/routes/api/items.js
  src/routes/api/pets.js
  src/routes/api/skills.js
  src/scripts/update-collections.js
  src/scripts/update-featured-profiles.js
  src/stats/bingo.js
  src/stats/dungeons.js
  src/stats/items.js
  src/stats/items/armor.js
  src/stats/items/category.js
  src/stats/items/museum.js
  src/stats/items/processing.js
  src/stats/leaderboards.js
  src/stats/misc.js
  src/stats/missing.js
  src/stats/pets.js
  src/stats/slayer.js
  tsconfig.json
Labels: size/XXL

#2184 merge development into production
  misc/benchmarks/get-texture.js
  package.json
  pnpm-lock.yaml
  public/resources/html/offline.html
  public/resources/scss/_fonts.scss
  public/resources/scss/index.scss
  public/resources/scss/shared.scss
  public/resources/scss/stats.scss
  public/resources/ts/calculate-player-stats.ts
  public/resources/ts/common-defer.ts
  public/resources/ts/development-defer.ts
  public/resources/ts/elements/bonus-stats.ts
  public/resources/ts/elements/guild-button.ts
  public/resources/ts/elements/inventory-view.ts
  public/resources/ts/elements/pack-list.ts
  public/resources/ts/elements/player-stat.ts
  public/resources/ts/elements/rich-item.ts
  public/resources/ts/elements/skill-component.ts
  public/resources/ts/elements/theme-list.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  public/resources/ts/tsconfig.json
  public/sw.js
  src/app.js
  src/constants/accessories.js
  src/constants/hotm.js
  src/constants/leveling.js
  src/constants/pet-stats.js
  src/constants/weight/lily-weight.js
  src/credentials.js
  src/custom-resources.js
  src/hashes.js
  src/helper.js
  src/lib.js
  src/main.js
  src/redis.js
  src/renderer.js
  src/routes/api/collections.js
  src/routes/api/items.js
  src/routes/api/pets.js
  src/routes/api/skills.js
  src/scripts/update-collections.js
  src/scripts/update-featured-profiles.js
  src/stats/bingo.js
  src/stats/dungeons.js
  src/stats/items.js
  src/stats/items/armor.js
  src/stats/items/category.js
  src/stats/items/museum.js
  src/stats/items/processing.js
  src/stats/leaderboards.js
  src/stats/misc.js
  src/stats/missing.js
  src/stats/pets.js
  src/stats/slayer.js
  tsconfig.json
Labels: size/XXL

#2185 Fix redis credentials issue
  src/credentials.js
  src/redis.js
Labels: size/S

#2186 Fix credentials issue
  src/credentials.js
  src/redis.js
Labels: size/S

#2187 fix: social xp beign NaN in coop
  src/stats/skills.js
Labels: size/XS

#2183 feat: add museum items
  src/constants/museum.js
Labels: size/XS

#2181 feat: add Taming Level Cap
  src/stats/skills.js
Labels: size/XS

#2174 feat: add description to inactive accessories
  views/sections/stats/items/accessories.ejs
Labels: size/XS

#2179 fix: hypixel beign hypixel
  src/lib.js
Labels: size/XS

#2182 feat: new December & January Pet Skins
  src/constants/skins-animations.js
Labels: size/L

#2178 fix: don't catch skycrypt erros in the update lb
  src/stats/leaderboards.js
Labels: size/XS

#2173 fix: embed once again
  views/stats.ejs
Labels: size/XS

#2180 fix: error caused by player using custom language translation
  src/stats/items/accessories.js
Labels: size/XS

#2189 Fix max level for Rainbow enchant
  common/constants/enchantments.js
Labels: size/XS

#2192 Hypixel plus updates
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/ui/icons/arrow_circle_red.properties
  src/custom-resources.js
  src/lib.js
  src/stats/items/processing.js
Labels: size/XS

#2193 Add Rose Dye to H+
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/dyes/dye_rose.gif
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/dyes/dye_rose.png
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/dyes/dye_rose.properties
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/runes/smitten_rune.png
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/runes/smitten_rune.properties
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/runes/smitten_rune_2.png
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/runes/smitten_rune_2.properties
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/runes/smitten_rune_3.png
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/items/runes/smitten_rune_3.properties
Labels: size/S

#2195 fix: getItemData() not applying glowing effect
  src/helper/item.js
Labels: size/XS

#2197 fix: revert redirecting
  src/app.js
Labels: size/XS

#2171 feat: include contests of backpacks into backpack value
  package.json
  pnpm-lock.yaml
  src/stats/items.js
  src/stats/items/processing.js
Labels: size/M

#2188 fix: races
  src/constants/misc.js
  src/stats/misc.js
  views/sections/stats/misc/races.ejs
Labels: size/L

#2172 fix: clean code & fix bestiary
  src/constants/bestiary.js
  src/stats/bestiary.js
  views/sections/stats/bestiary.ejs
Labels: size/XXL
