Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-01, with the labels that each got.

#2140 perf: improve `getTexture()` up to 5x
  misc/benchmarks/get-texture.js
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/arachne_armor/icons/arachne_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/aurora_armor/icons/burning/burning_aurora_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/aurora_armor/icons/fiery/fiery_aurora_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/aurora_armor/icons/hot/hot_aurora_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/aurora_armor/icons/infernal/infernal_aurora_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/aurora_armor/icons/normal/aurora_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/berserker_armor/icons/berserker_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/crimson_armor/icons/burning/burning_crimson_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/crimson_armor/icons/fiery/fiery_crimson_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/crimson_armor/icons/hot/hot_crimson_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/crimson_armor/icons/infernal/infernal_crimson_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/crimson_armor/icons/normal/crimson_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/ender_armor/icons/ender_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/ender_armor/icons/ender_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/ender_armor/icons/ender_helmet_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/ender_armor/icons/ender_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/fervor_armor/icons/burning/burning_fervor_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/fervor_armor/icons/fiery/fiery_fervor_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/fervor_armor/icons/hot/hot_fervor_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/fervor_armor/icons/infernal/infernal_fervor_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/fervor_armor/icons/normal/fervor_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/holy_dragon_armor/icons/holy_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/holy_dragon_armor/icons/holy_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/holy_dragon_armor/icons/holy_dragon_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/magma_lord_armor/icons/magma_lord_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/obsidian_chestplate/icons/obsidian_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/old_dragon_armor/icons/old_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/old_dragon_armor/icons/old_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/old_dragon_armor/icons/old_dragon_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/protector_dragon_armor/icons/protector_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/protector_dragon_armor/icons/protector_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/protector_dragon_armor/icons/protector_dragon_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/rampart_armor/icons/rampart_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/shimmering_light_armor/icons/shimmering_light_hood.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/strong_dragon_armor/icons/strong_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/strong_dragon_armor/icons/strong_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/strong_dragon_armor/icons/strong_dragon_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/superior_dragon_armor/icons/superior_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/superior_dragon_armor/icons/superior_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/superior_dragon_armor/icons/superior_dragon_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/terror_armor/icons/burning/burning_terror_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/terror_armor/icons/fiery/fiery_terror_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/terror_armor/icons/hot/hot_terror_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/terror_armor/icons/infernal/infernal_terror_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/terror_armor/icons/normal/terror_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/thunder_armor/icons/thunder_helmet.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/unstable_dragon_armor/icons/unstable_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/unstable_dragon_armor/icons/unstable_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/unstable_dragon_armor/icons/unstable_dragon_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/wise_dragon_armor/icons/wise_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/wise_dragon_armor/icons/wise_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/wise_dragon_armor/icons/wise_dragon_leggings_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/young_dragon_armor/icons/young_dragon_boots_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/young_dragon_armor/icons/young_dragon_chestplate_name.properties
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/equipment/armor/young_dragon_armor/icons/young_dragon_leggings_name.properties
  src/custom-resources.js
  src/stats/pets.js
  views/sections/stats/pets.ejs
Labels: size/L

#2141 fix: SB LvL component
  public/resources/ts/elements/skill-component.ts
  src/stats/leaderboards.js
Labels: size/M

#2142 perm/fix: personal compactor preview & ITEM caching
  src/constants/items.js
  src/helper/item.js
  src/scripts/init-collections.js
  src/scripts/update-collections.js
  src/stats/items/processing.js
  src/stats/mining.js
Labels: size/M

#2143 fix: error occured by skyhelper-networth
  src/lib.js
  src/stats/items/processing.js
Labels: size/M

#2144 fix: error caused by playing having no social
  views/stats.ejs
Labels: size/M

#2146 fix: error caused by corrupted protector
  src/stats/misc.js
Labels: size/XS

#2147 fix: error caused by kills
  src/constants/pet-stats.js
Labels: size/XS

#2148 fix: Hypixel returning profile without members
  src/lib.js
Labels: size/XS

#2149 fix: wrong error type used
  src/helper.js
Labels: size/XS

#2150 fix: hide missing pets if there r none
  views/sections/stats/pets.ejs
Labels: size/S

#2156 [URGENT] fix: bigInt error
  src/stats/items/processing.js
Labels: size/XS

#2151 perf: improve packs even futher
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/perks/mining_speed/ms_progress_viii.properties
  src/custom-resources.js
  src/helper.js
  src/routes/texture.js
  src/stats/items/mining.js
  src/stats/items/processing.js
Labels: size/L

#2152 fix: formatLore() not working on specific cases
  common/formatting.js
Labels: size/XS

#2154 fix: coins API endpoint
  src/app.js
  src/lib.js
  src/routes/apiv2/coins.js
Labels: size/M

#2155 fix: bingo data not shwon
  src/stats/bingo.js
  views/sections/stats/bingo.ejs
Labels: size/S

#2159 merge `development` into `production`
  common/formatting.js
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/perks/mining_speed/ms_progress_viii.properties
  src/app.js
  src/custom-resources.js
  src/helper.js
  src/lib.js
  src/routes/apiv2/coins.js
  src/routes/texture.js
  src/stats/bingo.js
  src/stats/items/mining.js
  src/stats/items/processing.js
  views/sections/stats/bingo.ejs
Labels: size/L

#2161 fix: add back skill tools
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
Labels: size/M

#2162 fix: boss colleciton grayscale
  views/sections/stats/collections.ejs
Labels: size/XS

#2163 perf: improve packs even further
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/item/accessories/book_of_progression/book_of_progression_common.properties
  src/custom-resources.js
  src/stats/items.js
Labels: size/M

#2158 Fixed Typos
  CONTRIBUTING.md
  README.md
Labels: size/S

#2165 merge development into production
  CONTRIBUTING.md
  README.md
  public/resourcepacks/FurfSky_Reborn_1_7/assets/minecraft/mcpatcher/cit/item/accessories/book_of_progression/book_of_progression_common.properties
  src/custom-resources.js
  src/stats/items.js
  views/sections/stats/collections.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
Labels: size/L

#2166 fix favorite arrow formatting
  src/stats/misc.js
Labels: size/XS

#2167 fix: hide pets in navbar
  src/stats/pets.js
Labels: size/XS

#2168 fix: hide minions if not unlocked
  views/stats.ejs
Labels: size/XS

#2169 fix: unqiue accessories count & dupes
  src/lib.js
  src/stats/missing.js
  views/sections/stats/items/accessories.ejs
Labels: size/M

#2170 fix: museum item display names
  src/stats/items/museum.js
Labels: size/XS

#2176 merge development into production
  src/lib.js
  src/scripts/init-collections.js
  src/stats/items/museum.js
  src/stats/misc.js
  src/stats/missing.js
  src/stats/pets.js
  views/sections/stats/items/accessories.ejs
  views/stats.ejs
Labels: size/M
