Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-04, with the labels that each got.

#2217 revert april fools changes
  includes/footer.ejs
  includes/header.ejs
  package.json
  pnpm-lock.yaml
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/accessories/general_medallion.png
  public/resources/img/themes/owo/bg.webp
  public/resources/img/themes/owo/bg2.webp
  public/resources/scss/stats.scss
  public/resources/themes/default.json
  public/resources/ts/common-defer.ts
  public/resources/ts/elements/bonus-stats.ts
  public/resources/ts/elements/guild-button.ts
  public/resources/ts/elements/pack-list.ts
  public/resources/ts/elements/player-stat.ts
  public/resources/ts/elements/skill-component.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  src/app.js
  src/constants/owo/Word.js
  src/constants/owo/formatting.js
  src/constants/owo/index.js
  src/helper.js
  src/lib.js
  src/renderer.js
  views/index.ejs
  views/sections/stats/basic_stats.ejs
  views/sections/stats/bestiary.ejs
  views/sections/stats/dungeons.ejs
  views/sections/stats/items/armor.ejs
  views/sections/stats/items/inventory.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/claimed_items.ejs
  views/sections/stats/misc/damage.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/essence.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/stats.ejs
Labels: size/XL

#2218 merge development into production
  includes/footer.ejs
  includes/header.ejs
  package.json
  pnpm-lock.yaml
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/accessories/general_medallion.png
  public/resources/img/themes/owo/bg.webp
  public/resources/img/themes/owo/bg2.webp
  public/resources/scss/stats.scss
  public/resources/themes/default.json
  public/resources/ts/common-defer.ts
  public/resources/ts/elements/bonus-stats.ts
  public/resources/ts/elements/guild-button.ts
  public/resources/ts/elements/pack-list.ts
  public/resources/ts/elements/player-stat.ts
  public/resources/ts/elements/skill-component.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  src/app.js
  src/constants/owo/Word.js
  src/constants/owo/formatting.js
  src/constants/owo/index.js
  src/helper.js
  src/lib.js
  src/renderer.js
  views/index.ejs
  views/sections/stats/basic_stats.ejs
  views/sections/stats/bestiary.ejs
  views/sections/stats/dungeons.ejs
  views/sections/stats/items/armor.ejs
  views/sections/stats/items/inventory.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/claimed_items.ejs
  views/sections/stats/misc/damage.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/essence.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/stats.ejs
Labels: size/XL

#2219 use mat api
  src/helper.js
Labels: size/XS

#2221 [URGENT] fix: twemojis breaking, feat: add april fools theme
  includes/footer.ejs
  includes/header.ejs
  public/resources/img/themes/april-fools-2024/bg.png
  public/resources/img/themes/april-fools-2024/bg.webp
  public/resources/scss/shared.scss
  public/resources/themes/april-fools-2024.json
  public/resources/ts/elements/theme-list.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  src/app.js
  src/constants/themes/april-fools-2024/formatting.js
  src/constants/themes/april-fools-2024/index.js
  src/constants/themes/april-fools-2024/word.js
  src/stats/pets.js
  views/index.ejs
  views/sections/stats/dungeons.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/claimed_items.ejs
  views/sections/stats/misc/damage.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/essence.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/sections/stats/slayer.ejs
  views/stats.ejs
Labels: size/L

#2222 fix: message for ironamn and bingo profiles
  views/stats.ejs
Labels: size/XS

#2223 feat: add new pet skins
  src/constants/skins-animations.js
Labels: size/L

#2220 0.19.12 pet stats update
  common/constants/stats.js
  src/constants/pet-stats.js
Labels: size/L

#2224 merge development into production
  common/constants/stats.js
  includes/footer.ejs
  includes/header.ejs
  public/resources/img/themes/april-fools-2024/bg.png
  public/resources/img/themes/april-fools-2024/bg.webp
  public/resources/scss/shared.scss
  public/resources/themes/april-fools-2024.json
  public/resources/ts/elements/theme-list.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  src/app.js
  src/constants/pet-stats.js
  src/constants/skins-animations.js
  src/constants/themes/april-fools-2024/formatting.js
  src/constants/themes/april-fools-2024/index.js
  src/constants/themes/april-fools-2024/word.js
  src/helper.js
  src/stats/pets.js
  views/index.ejs
  views/sections/stats/dungeons.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/claimed_items.ejs
  views/sections/stats/misc/damage.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/essence.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/sections/stats/slayer.ejs
  views/stats.ejs
Labels: size/XL

#2226 fix: items error
  src/constants/hotm.js
  src/constants/pet-stats.js
  src/helper.js
  src/stats/items/mining.js
Labels: size/S

#2227 merge development into production
  src/constants/hotm.js
  src/constants/pet-stats.js
  src/helper.js
  src/stats/items/mining.js
Labels: size/S

#2228 feat: new gemstones
  src/constants/gemstones.js
Labels: size/M

#2229 merge development into production
  src/constants/gemstones.js
Labels: size/M

#2230 merge development into production
  package.json
  pnpm-lock.yaml
Labels: size/M

#2231 Update CI/CD yml badge
  README.md
  public/resources/themes/warpwing.json
  src/scripts/update-featured-profiles.js
Labels: size/XS

#2232 fix: dungeons error
  src/helper.js
  views/sections/stats/dungeons.ejs
Labels: size/S

#2233 Added COREPACK to bypass pnpm version check on Dockerfile
  Dockerfile
Labels: size/XS

#2237 feat: add T texture for hotm tree
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_i.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_i.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_ii.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_ii.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_iii.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_iii.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_iv.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_iv.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_locked.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_locked.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_unlocked.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_unlocked.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_v.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_v.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_vi.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_vi.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_vii.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_vii.properties
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_viii.png
  public/resourcepacks/RNBW+_0_7/assets/minecraft/mcpatcher/cit/gui_icons/mountain_heart/tree/top/top_viii.properties
  src/constants/hotm.js
Labels: size/M

#2239 fix: pets getting duplicated in the nw calculation
  src/stats/pets.js
Labels: size/XS

#2240 feat: add new enchantmnets
  common/constants/enchantments.js
Labels: size/XS

#2241 feat: add new fairy souls
  src/constants/misc.js
Labels: size/XS

#2242 feat: add new glacite mineshaft location
  src/constants/misc.js
Labels: size/XS

#2243 feat: add new forge items
  src/constants/forge.js
  src/stats/mining.js
  views/sections/stats/skills/mining.ejs
Labels: size/M

#2244 fix: display secrets per profile and not from achievement
  src/lib.js
  src/routes/apiv2/dungeons.js
  src/stats/dungeons.js
  views/sections/stats/dungeons.ejs
Labels: size/M

#2245 feat: add new mining v3 pets
  src/constants/pet-stats.js
  src/constants/pets.js
  src/stats/pets.js
Labels: size/L

#2246 merge development into production
  common/constants/enchantments.js
  src/constants/forge.js
  src/constants/misc.js
  src/constants/pet-stats.js
  src/constants/pets.js
  src/lib.js
  src/routes/apiv2/dungeons.js
  src/stats/dungeons.js
  src/stats/mining.js
  src/stats/pets.js
  views/sections/stats/dungeons.ejs
  views/sections/stats/skills/mining.ejs
Labels: size/XL
