Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-03, with the labels that each got.

#2202 fix: fixed issue with stats calculator
  public/resources/ts/calculate-player-stats.ts
Labels: size/XS

#2203 Fixed more issues with stats calculator & Added Ice and Gold Essence shops
  common/constants/bonuses.js
  public/resources/ts/calculate-player-stats.ts
  src/constants/misc.js
Labels: size/M

#2196 feat: error handling for items processing && fix: API endpoints
  src/app.js
  src/helper.js
  src/lib.js
  src/routes/api/accessories.js
  src/routes/api/armor.js
  src/routes/api/cakebag.js
  src/routes/api/collections.js
  src/routes/api/items.js
  src/routes/api/minions.js
  src/routes/api/pets.js
  src/routes/api/profiles.js
  src/routes/api/skills.js
  src/routes/api/wardrobe.js
  src/routes/api/weapons.js
  src/routes/apiv2/coins.js
  src/routes/apiv2/dungeons.js
  src/routes/apiv2/profile.js
  src/routes/apiv2/slayers.js
  src/routes/apiv2/talismans.js
  src/stats.js
  src/stats/items.js
  src/stats/leaderboards.js
  src/stats/missing.js
  src/stats/networth.js
  src/stats/pets.js
  views/sections/stats/skills/mining.ejs
Labels: size/XXL

#2211 April fools2024
  includes/footer.ejs
  includes/header.ejs
  package.json
  pnpm-lock.yaml
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/accessories/general_medallion.png
  public/resources/img/themes/owo/bg.webp
  public/resources/img/themes/owo/bg2.webp
  public/resources/scss/stats.scss
  public/resources/themes/default.json
  public/resources/ts/common-defer.ts
  public/resources/ts/elements/bonus-stats.ts
  public/resources/ts/elements/guild-button.ts
  public/resources/ts/elements/pack-list.ts
  public/resources/ts/elements/player-stat.ts
  public/resources/ts/elements/skill-component.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  src/app.js
  src/constants/owo/Word.js
  src/constants/owo/formatting.js
  src/constants/owo/index.js
  src/helper.js
  src/lib.js
  src/renderer.js
  views/index.ejs
  views/sections/stats/basic_stats.ejs
  views/sections/stats/bestiary.ejs
  views/sections/stats/dungeons.ejs
  views/sections/stats/items/armor.ejs
  views/sections/stats/items/inventory.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/claimed_items.ejs
  views/sections/stats/misc/damage.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/essence.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/stats.ejs
Labels: size/XL

#2214 april fools 2024
  includes/footer.ejs
  includes/header.ejs
  package.json
  pnpm-lock.yaml
  public/resourcepacks/Hypixel_Plus/assets/minecraft/mcpatcher/cit/skyblock/accessories/general_medallion.png
  public/resources/img/themes/owo/bg.webp
  public/resources/img/themes/owo/bg2.webp
  public/resources/scss/stats.scss
  public/resources/themes/default.json
  public/resources/ts/common-defer.ts
  public/resources/ts/elements/bonus-stats.ts
  public/resources/ts/elements/guild-button.ts
  public/resources/ts/elements/pack-list.ts
  public/resources/ts/elements/player-stat.ts
  public/resources/ts/elements/skill-component.ts
  public/resources/ts/stats-defer.ts
  public/resources/ts/themes.ts
  src/app.js
  src/constants/owo/Word.js
  src/constants/owo/formatting.js
  src/constants/owo/index.js
  src/helper.js
  src/lib.js
  src/renderer.js
  views/index.ejs
  views/sections/stats/basic_stats.ejs
  views/sections/stats/bestiary.ejs
  views/sections/stats/dungeons.ejs
  views/sections/stats/items/armor.ejs
  views/sections/stats/items/inventory.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/claimed_items.ejs
  views/sections/stats/misc/damage.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/essence.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/stats.ejs
Labels: size/XL
