Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-11, with the labels that each got.

#2307 Fix accessories
  src/constants/accessories.js
  src/stats/missing.js
  views/sections/stats/items/accessories.ejs
Labels: size/XS

#2289 fix: fastest kill time displaying incorrectly when below 1s and tooltips displaying without there being anything to display
  views/sections/stats/misc/end_island.ejs
Labels: size/S

#2308 merge development into production
  src/constants/accessories.js
  src/stats/missing.js
  views/sections/stats/items/accessories.ejs
  views/sections/stats/misc/end_island.ejs
  views/stats.ejs
Labels: size/M

#2310 feat: hide patreon banner if profile has emoji
  views/stats.ejs
Labels: size/XS

#2311 fix: dungeon class lbs not displaying
  src/stats/dungeons.js
Labels: size/XS

#2309 Add new Bal stats + fix cold resistance typo
  common/constants/stats.js
  src/constants/hotm.js
  src/constants/pet-stats.js
  src/constants/pets.js
Labels: size/M

#2312 merge development into production
  common/constants/stats.js
  src/constants/hotm.js
  src/constants/pet-stats.js
  src/constants/pets.js
  src/stats/dungeons.js
  views/stats.ejs
Labels: size/M
