Repository SkyCryptWebsite/SkyCrypt, pull requests merged in 2024-09, with the labels that each got.

#2269 Fix rank plus background gap
  includes/header.ejs
  public/resources/scss/stats.scss
Labels: size/XS

#2274 fix: fix cache only
  src/app.js
Labels: size/XS

#2275 Merge development into production
  includes/header.ejs
  public/resources/scss/stats.scss
  src/app.js
Labels: size/XS

#2272 IMPROVEMENT: added stranded zealots
  src/constants/bestiary.js
Labels: size/XS

#2268 Update accessory constants
  src/constants/accessories.js
Labels: size/XS

#2267 fix: remove profile name check
  src/stats/leaderboards.js
Labels: size/XS

#2277 Add cache times to credentials.json
  src/cachetimes.js
  src/credentials.js
  src/lib.js
Labels: size/L

#2278 feat: add elite to buttons
  views/stats.ejs
Labels: size/M

#2279 merge development into production
  src/cachetimes.js
  src/credentials.js
  src/lib.js
  views/stats.ejs
Labels: size/L

#2281 Fix the farming skill section
  src/constants/weight/farming-weight.js
  src/lib.js
  src/stats/farming.js
  views/stats.ejs
Labels: size/L

#2282 Fix styling
  src/constants/weight/farming-weight.js
  src/stats/items.js
  views/sections/stats/basic_stats.ejs
  views/sections/stats/bestiary.ejs
  views/sections/stats/bingo.ejs
  views/sections/stats/collections.ejs
  views/sections/stats/crimson_isle.ejs
  views/sections/stats/items/accessories.ejs
  views/sections/stats/items/inventory.ejs
  views/sections/stats/minions.ejs
  views/sections/stats/misc.ejs
  views/sections/stats/misc/auctions.ejs
  views/sections/stats/misc/end_island.ejs
  views/sections/stats/misc/kills_deaths.ejs
  views/sections/stats/misc/milestones.ejs
  views/sections/stats/misc/mythological_event.ejs
  views/sections/stats/misc/potion_effects.ejs
  views/sections/stats/misc/profile_upgrades.ejs
  views/sections/stats/misc/races.ejs
  views/sections/stats/misc/uncategorized.ejs
  views/sections/stats/misc/winter_island.ejs
  views/sections/stats/pets.ejs
  views/sections/stats/rift.ejs
  views/sections/stats/skills.ejs
  views/sections/stats/skills/enchanting.ejs
  views/sections/stats/skills/farming.ejs
  views/sections/stats/skills/fishing.ejs
  views/sections/stats/skills/mining.ejs
  views/sections/stats/slayer.ejs
Labels: size/L
